### ISSUE TITLE
might brackets help in the linear model equation?

### ISSUE THREAD

**Issue by ajstewartlang** [carpentries-incubator/simple-linear-regression-public-health#13] opened 2021-07-12 14:35 UTC
I'm not sure how maths-y everyone taking this lesson will be - adding brackets around the predictor and slope to make it clearer that it's these two terms that are multiplied together might help.

**Comment by ajstewartlang** [comment] 2021-07-12 14:39
Is te equation for a linear model or linear regression? If it's regression then adding a + residual term might help (and make it clearer there will also be some error in prediction).

**Comment by ezherman** [comment] 2021-07-15 15:48
Hi @ajstewartlang, thanks for these. 

In terms of brackets, I will keep this in mind in the first run of the workshop and see if the multiplication is something students struggle with. If it is then I will include the brackets when implementing student feedback. 

I opted for leaving out the residual term from the equation for a few reasons:
- The equation in terms of the expectation, rather than individual observations, is probably easier to grasp for students as it leaves out subscripts indicating individual observations. 
- The equation in terms of the expectation also highlights that we are (in this workshop) primarily interested in the mean, rather than individual observations. 
- I built the explanation of the logistic regression model on the linear regression model. Since the logistic regression model equation does not include an error term, I thought it would evade confusion to leave out the error term here as well.

We do return to the error aspect of the model in the assumptions episode, where the meaning of residuals is explored visually. Do you think this is sufficient, or should students be introduced to residuals in equation form as well?

**Comment by ezherman** [comment] 2022-05-14 16:37
I have not found that learners struggle with the current formulation of the regression equation, so I will close this issue.

**Closed by ezherman** 2022-05-14 16:37 UTC
